language: go
sudo: required
go:
  - 1.5.3
install:
  - go get golang.org/x/sys/unix
  - go get github.com/tools/godep
  - godep restore
  - make all
services:
  - docker
branches:
  only:
    - master